# Generated by Django 2.1.15 on 2021-01-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoncoRNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('journal', models.CharField(max_length=255)),
                ('pub_time', models.CharField(max_length=10)),
                ('pmid', models.CharField(max_length=20)),
                ('database_id', models.CharField(max_length=20)),
                ('ncrna_id', models.CharField(max_length=50)),
                ('ncrna_name', models.CharField(max_length=50)),
                ('ncrna_type', models.CharField(max_length=30)),
                ('drug_id', models.CharField(max_length=200)),
                ('drug_name', models.CharField(max_length=100)),
                ('cancer_type', models.CharField(max_length=100)),
                ('method_ncrna', models.CharField(max_length=100)),
                ('method_drug', models.TextField()),
                ('tissue', models.CharField(max_length=255)),
                ('ncrna_exp_pattern', models.CharField(max_length=255)),
                ('sensitive_or_resistant', models.CharField(max_length=255)),
                ('major_targets', models.CharField(max_length=255)),
                ('target_gene', models.CharField(max_length=255)),
                ('pathway', models.CharField(max_length=255)),
                ('evidence_code', models.CharField(max_length=255)),
            ],
        ),
    ]
